fos_user_group_list:
    path: /list
    defaults: { _controller: FOSUserBundle:Group:list }

fos_user_group_new:
    path: /new
    defaults: { _controller: FOSUserBundle:Group:new }


fos_user_group_show:
    path: /{groupName}
    defaults: { _controller: FOSUserBundle:Group:show }

fos_user_group_edit:
    path: /{groupName}/edit
    defaults: { _controller: FOSUserBundle:Group:edit }

fos_user_group_delete:
    path: /{groupName}/delete
    defaults: { _controller: FOSUserBundle:Group:delete }
