fos_user_registration_register:
    path: /
    defaults: { _controller: FOSUserBundle:Registration:register }

fos_user_registration_check_email:
    path: /check-email
    defaults: { _controller: FOSUserBundle:Registration:checkEmail }

fos_user_registration_confirm:
    path: /confirm/{token}
    defaults: { _controller: FOSUserBundle:Registration:confirm }

fos_user_registration_confirmed:
    path: /confirmed
    defaults: { _controller: FOSUserBundle:Registration:confirmed }
