<?php

namespace AdminBundle\Repository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPlaylistUser($idUser) {
        
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder('p')
            ->where("p.genre = :id")
            ->setParameter('id', $idUser);

        return $qb->getQuery()->getResult();
    }
}
