<?php

namespace AdminBundle\Repository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends \Doctrine\ORM\EntityRepository
{
    public function authorPlaylist($idPlaylist) {
        $qb = $this
            ->createQueryBuilder('p')
            ->innerJoin("p.author", 'u')
            ->where('p.id = :idPlaylist')
            ->setParameter('idPlaylist', $idPlaylist)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
