<?php

namespace FrontBundle\Repository;

/**
 * MusicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MusicRepository extends \Doctrine\ORM\EntityRepository
{
    public function musicPlaylist($idPlaylist) {
        $qb = $this
            ->createQueryBuilder('m')
            ->innerJoin('m.playlist', 'p')
            ->where('p.id = :idPlaylist')
            ->setParameter('idPlaylist', $idPlaylist)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
